name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Instalar o python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'
      
      - name: Instalar o uv
        run: pipx install uv

      - name: Instalar dependências
        run: uv sync --locked --all-extras --dev
      
      - name: Executar testes
        run: task test